name: hc_experiment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy=2.2.6
  - pandas=2.2.3
  - matplotlib=3.10.3
  - scikit-learn
  - jupyter
  - ipykernel
  - pip:
    - absl-py==2.3.0
    - aimedic-pkg @ git+https://github.com/AIMedic-dev/aimedic-pkg.git@3693e415f4f2307a4f9178ea66f5c847c12b26d3
    - annotated-types==0.7.0
    - anyio==3.7.1
    - asttokens==3.0.0
    - attrs==25.3.0
    - bcrypt==4.3.0
    - bert-score==0.3.13
    - blinker==1.9.0
    - blis==1.3.0
    - catalogue==2.0.10
    - certifi==2025.1.31
    - chardet==5.2.0
    - charset-normalizer==3.4.1
    - click==8.1.8
    - cloudpathlib==0.21.0
    - colorama==0.4.6
    - comm==0.2.2
    - confection==0.1.5
    - contourpy==1.3.2
    - cycler==0.12.1
    - cymem==2.0.11
    - debugpy==1.8.14
    - decorator==5.2.1
    - distro==1.9.0
    - dnspython==2.7.0
    - es_core_news_md @ https://github.com/explosion/spacy-models/releases/download/es_core_news_md-3.8.0/es_core_news_md-3.8.0-py3-none-any.whl#sha256=478b8bb3f3e8eb149192f7d80e7cd64f990b7e9bccbc5329df41a57e86326be2
    - et_xmlfile==2.0.0
    - executing==2.2.0
    - fastapi==0.104.1
    - filelock==3.18.0
    - flasgger==0.9.7.1
    - Flask==2.3.2
    - fonttools==4.58.4
    - fsspec==2025.3.2
    - git-filter-repo==2.47.0
    - greenlet==3.1.1
    - h11==0.16.0
    - httpcore==1.0.9
    - httpx==0.28.1
    - huggingface-hub==0.30.2
    - idna==3.10
    - ipython==9.3.0
    - ipython_pygments_lexers==1.1.1
    - itsdangerous==2.2.0
    - jedi==0.19.2
    - Jinja2==3.1.5
    - jiter==0.10.0
    - joblib==1.5.1
    - jsonpatch==1.33
    - jsonpointer==3.0.0
    - jsonschema==4.24.0
    - jsonschema-specifications==2025.4.1
    - jupyter_client==8.6.3
    - jupyter_core==5.8.1
    - kiwisolver==1.4.8
    - langchain==0.3.25
    - langchain-core==0.3.64
    - langchain-openai==0.3.21
    - langchain-text-splitters==0.3.8
    - langcodes==3.5.0
    - langgraph==0.4.8
    - langgraph-checkpoint==2.0.26
    - langgraph-prebuilt==0.2.2
    - langgraph-sdk==0.1.70
    - langsmith==0.3.45
    - language_data==1.3.0
    - marisa-trie==1.2.1
    - markdown-it-py==3.0.0
    - MarkupSafe==3.0.2
    - matplotlib-inline==0.1.7
    - mdurl==0.1.2
    - mistune==3.1.3
    - mpmath==1.3.0
    - murmurhash==1.0.12
    - nest-asyncio==1.6.0
    - networkx==3.4.2
    - nltk==3.9.1
    - openai==1.84.0
    - openpyxl==3.1.5
    - orjson==3.10.18
    - ormsgpack==1.10.0
    - packaging==24.2
    - parso==0.8.4
    - passlib==1.7.4
    - pillow==11.1.0
    - platformdirs==4.3.8
    - preshed==3.0.9
    - prompt_toolkit==3.0.51
    - psutil==7.0.0
    - psycopg2-binary==2.9.10
    - pure_eval==0.2.3
    - pyaes==1.6.1
    - pycryptodome==3.21.0
    - pydantic==2.11.4
    - pydantic_core==2.33.2
    - pyDes==2.0.1
    - Pygments==2.19.1
    - pymongo==4.13.0
    - pyodbc==5.2.0
    - pyparsing==3.2.3
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.0.0
    - python-multipart==0.0.20
    - pytz==2025.1
    - pyxlsb==1.0.10
    - PyYAML==6.0.2
    - pyzmq==27.0.0
    - referencing==0.36.2
    - regex==2024.11.6
    - requests==2.32.3
    - requests-toolbelt==1.0.0
    - rich==14.0.0
    - rouge_score==0.1.2
    - rpds-py==0.25.1
    - safetensors==0.5.3
    - scapy==2.6.1
    - setuptools==80.3.0
    - shellingham==1.5.4
    - six==1.17.0
    - smart-open==7.1.0
    - sniffio==1.3.1
    - spacy==3.8.5
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.5
    - SQLAlchemy==2.0.39
    - srsly==2.5.1
    - stack-data==0.6.3
    - starlette==0.27.0
    - sympy==1.14.0
    - tenacity==9.1.2
    - thinc==8.3.6
    - tiktoken==0.9.0
    - tokenizers==0.21.1
    - torch==2.7.0
    - tornado==6.5.1
    - tqdm==4.67.1
    - traitlets==5.14.3
    - transformers==4.51.3
    - typer==0.15.3
    - typing-inspection==0.4.0
    - typing_extensions==4.12.2
    - tzdata==2025.1
    - urllib3==2.3.0
    - uvicorn==0.24.0
    - wasabi==1.1.3
    - wcwidth==0.2.13
    - weasel==0.4.1
    - websockets==15.0.1
    - Werkzeug==3.1.3
    - wrapt==1.17.2
    - xxhash==3.5.0
    - zstandard==0.23.0 